### ISSUE TITLE
/backend/start.sh: not found

### ISSUE THREAD

**Issue by bootsch** [ynput/ayon-docker#7]
Tried to run the ayon-docker but got this error.
I cloned this repos and followed the instructions in the readme file.

The 'backend' directory is created but empty.

Running this on Window 11, Docker Compose version v2.15.1

**Comment by martastain** [comment]
Hello,
backend directory is not really needed at all if you are not changing the server code. You can just comment out `- "./backend:/backend"` line from the `volumes` section of the docker-compose.yml and on windows, comment out or delete ` - "/etc/localtime:/etc/localtime:ro"` as well. 

The reason for having the backend directory mounted to the container is to be able to work on the server code without rebuilding the image, but since it is not the default setup, I'll remove it in the repository.

**Comment by bootsch** [comment]
Unfortunately I get the same error when I comment out backend, in fact, I have all volumes commented out, see below in snippet from my docker-compose.yml
```
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./addons:/addons"
      - "./backend:/backend"
      - "./storage:/storage"
```

**Comment by martastain** [comment]
that snippet shows active volumes (not commented out). You may try to remove them completely and keep just addons and storage there:

```
    volumes:
      - "./addons:/addons"
      - "./storage:/storage"
```

Note that you need to shut down the stack completely (using docker-compose down), in order for these changes to take effect.

**Comment by bootsch** [comment]
Ok, clear. I guess my yaml is a bit rusty.
Just to be sure I made a fresh clone of this repos, made no changes and could successfully start.

I guess it was my bad not understanding the yaml file.
I removed the double quotes around `- "./backend:/backend"`

**Comment by bootsch** [comment]
Thanks for the fast support

**Comment by tweak-wtf** [comment]
hey folks... i've ran into the same issue.
I just changed all line terminators of shell files to from CRLF (windows) to LF (unix)... this did the trick for me
